name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      odoo:
        image: odoo:16
        ports:
          - 8069:8069
        env:
          HOST: db
          USER: admin
          PASSWORD: admin
        options: >-
          --health-cmd="curl --fail http://localhost:8069/web/login || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build library
        run: npm run build

      - name: Start proxy server
        run: nohup node proxy-server.js > proxy.log 2>&1 &

      - name: Wait for proxy
        run: |
          for i in {1..20}; do
            curl -s http://localhost:3000 && break
            echo "Waiting for proxy..."
            sleep 2
          done

      - name: Run Playwright tests
        run: npm run test-browser
