name: Run Vitest Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vitest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odoo"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      odoo:
        image: odoo:16
        ports:
          - 8069:8069
        env:
          HOST: postgres
          USER: odoo
          PASSWORD: odoo
          POSTGRES_DB: test
          PGHOST: postgres
        options: >-
          --health-cmd="curl --fail http://localhost:8069/web/login || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Wait for Odoo to be ready
        run: |
          for i in {1..30}; do
            curl -s http://localhost:8069/web/login && break
            echo "Waiting for Odoo..."
            sleep 3
          done

      - name: Run Vitest
        run: npm run test
